WeatherService/Controllers/WeatherUiController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net;
using System.Web.Mvc;
using WeatherService.Models;

namespace WeatherService.Controllers
{
    public class WeatherUiController : Controller
    {
        // GET: WeatherUi
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        // POST: WeatherUi
        [HttpPost]
        public ActionResult Index(WeatherData weatherData)
        {
            weatherData.AverageTemperature = string.Empty;
            weatherData.AverageWindSpeed = string.Empty;
            if (weatherData.Location == null)
            {
                ViewBag.ErrorDescription = "You must supply a location";
                ModelState.Clear();
                return View(weatherData);
            }

            var client = new RestClient("http://localhost:50082/api");
            var request = new RestRequest("weather/" + weatherData.Location);
            var response = client.Execute(request);
            if (response.StatusCode != HttpStatusCode.OK)
            {
                ViewBag.ErrorDescription = "An error has occurred calling WeatherFinder service";
                ModelState.Clear();
                return View(weatherData);
            }
            var results = JsonConvert.DeserializeObject<AverageWeatherResult>(response.Content);
            if (results.Status != HttpStatusCode.OK)
            {
                ViewBag.ErrorDescription = "An error has occurred calling a weather provider";
                ModelState.Clear();
                return View(weatherData);
            }
            switch (weatherData.TemperatureUnits)
            {
                case "Celsius":
                    weatherData.AverageTemperature = Math.Round(results.AverageTemperatureCelsius).ToString();
                    break;
                case "Fahrenheit":
                    weatherData.AverageTemperature = Math.Round(results.AverageTemperatureFahrenheit).ToString();
                    break;
            }
            switch (weatherData.WindSpeedUnits)
            {
                case "Kph":
                    weatherData.AverageWindSpeed = Math.Round(results.AverageWindSpeedKph).ToString();
                    break;
                case "Mph":
                    weatherData.AverageWindSpeed = Math.Round(results.AverageWindSpeedMph).ToString();
                    break;
            }

            ViewBag.ErrorDescription = string.Empty;
            ModelState.Clear();
            return View(weatherData);
        }
    }
}

WeatherService/Views/WeatherUi/Index.cshtml
@model WeatherService.Models.WeatherData

<div class="jumbotron">
    <h1>Weather Finder Application</h1>
    <p>Find the average weather from several providers.</p>
</div>
<div class="container">

        @using (Html.BeginForm("Index", "WeatherUi", FormMethod.Post))
        {
            <div class="form-horizontal">
                <div class="col-md-6">
                    @Html.AntiForgeryToken()

                    <div class="form-group">
                        @Html.LabelFor(m => m.Location, new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(m => m.Location, new { @class = "form-control" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(m => m.TemperatureUnits, new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.DropDownListFor(m => m.TemperatureUnits,
                        new List<SelectListItem>{
                            new SelectListItem {Value="Celsius", Text="Celsius"},
                            new SelectListItem {Value="Fahrenheit", Text="Fahrenheit"}
                        },
                        new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">           
                        @Html.LabelFor(m => m.WindSpeedUnits, new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                        @Html.DropDownListFor(m => m.WindSpeedUnits,
                        new List<SelectListItem>{
                            new SelectListItem {Value="Kph", Text="Kph"},
                            new SelectListItem {Value="Mph", Text="Mph"}
                        },
                        new { @class = "form-control" })
                        </div>
                    </div>

                    <div class="col-md-12">
                        <input type="submit" class="btn btn-default" value="Submit" />
                    </div>

                    <div class="col-md-12">
                        <span class="text-danger">@ViewBag.ErrorDescription</span>
                    </div>

                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.AverageTemperature, new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                        @Html.TextBoxFor(m => m.AverageTemperature, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.AverageWindSpeed, new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                        @Html.TextBoxFor(m => m.AverageWindSpeed, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>
                </div>
            </div>
        }

</div>